#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint `git diff --name-only --staged --diff-filter=d | tr '\n' ' '`
npm run format `git diff --name-only --staged --diff-filter=d | grep "^src/" | tr '\n' ' '`
git add `git diff --name-only --staged --diff-filter=d | grep "^src/" | tr '\n' ' '`
